/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface DCLBillboardInterface extends ethers.utils.Interface {
  functions: {
    "bannerCount()": FunctionFragment;
    "banners(uint256)": FunctionFragment;
    "billboardCount()": FunctionFragment;
    "billboards(uint256)": FunctionFragment;
    "createBanner(string,string,string)": FunctionFragment;
    "createBillboard(string,string,string,uint256)": FunctionFragment;
    "createFlight(string,uint256,uint256,uint256,uint256,uint256)": FunctionFragment;
    "flightCount()": FunctionFragment;
    "flights(uint256)": FunctionFragment;
    "name()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "bannerCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "banners",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "billboardCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "billboards",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createBanner",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createBillboard",
    values: [string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createFlight",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "flightCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "flights",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "bannerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "banners", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "billboardCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "billboards", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createBanner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createBillboard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createFlight",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "flightCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "flights", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;

  events: {
    "BannerCreated(tuple)": EventFragment;
    "BillboardCreated(tuple)": EventFragment;
    "FlightCreated(tuple)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BannerCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BillboardCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FlightCreated"): EventFragment;
}

export class DCLBillboard extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: DCLBillboardInterface;

  functions: {
    bannerCount(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "bannerCount()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    banners(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      id: BigNumber;
      hash: string;
      description: string;
      clickThru: string;
      owner: string;
      0: BigNumber;
      1: string;
      2: string;
      3: string;
      4: string;
    }>;

    "banners(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      id: BigNumber;
      hash: string;
      description: string;
      clickThru: string;
      owner: string;
      0: BigNumber;
      1: string;
      2: string;
      3: string;
      4: string;
    }>;

    billboardCount(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "billboardCount()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    billboards(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      id: BigNumber;
      description: string;
      parcel: string;
      realm: string;
      rate: BigNumber;
      owner: string;
      0: BigNumber;
      1: string;
      2: string;
      3: string;
      4: BigNumber;
      5: string;
    }>;

    "billboards(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      id: BigNumber;
      description: string;
      parcel: string;
      realm: string;
      rate: BigNumber;
      owner: string;
      0: BigNumber;
      1: string;
      2: string;
      3: string;
      4: BigNumber;
      5: string;
    }>;

    createBanner(
      _bannerHash: string,
      _description: string,
      _clickThru: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "createBanner(string,string,string)"(
      _bannerHash: string,
      _description: string,
      _clickThru: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    createBillboard(
      _description: string,
      _parcel: string,
      _realm: string,
      _rate: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "createBillboard(string,string,string,uint256)"(
      _description: string,
      _parcel: string,
      _realm: string,
      _rate: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    createFlight(
      _description: string,
      _bannerId: BigNumberish,
      _billboardId: BigNumberish,
      _rate: BigNumberish,
      _startDate: BigNumberish,
      _endDate: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "createFlight(string,uint256,uint256,uint256,uint256,uint256)"(
      _description: string,
      _bannerId: BigNumberish,
      _billboardId: BigNumberish,
      _rate: BigNumberish,
      _startDate: BigNumberish,
      _endDate: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    flightCount(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "flightCount()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    flights(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      id: BigNumber;
      description: string;
      bannerId: BigNumber;
      billboardId: BigNumber;
      rate: BigNumber;
      startDate: BigNumber;
      endDate: BigNumber;
      0: BigNumber;
      1: string;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
      5: BigNumber;
      6: BigNumber;
    }>;

    "flights(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      id: BigNumber;
      description: string;
      bannerId: BigNumber;
      billboardId: BigNumber;
      rate: BigNumber;
      startDate: BigNumber;
      endDate: BigNumber;
      0: BigNumber;
      1: string;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
      5: BigNumber;
      6: BigNumber;
    }>;

    name(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "name()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;
  };

  bannerCount(overrides?: CallOverrides): Promise<BigNumber>;

  "bannerCount()"(overrides?: CallOverrides): Promise<BigNumber>;

  banners(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    id: BigNumber;
    hash: string;
    description: string;
    clickThru: string;
    owner: string;
    0: BigNumber;
    1: string;
    2: string;
    3: string;
    4: string;
  }>;

  "banners(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    id: BigNumber;
    hash: string;
    description: string;
    clickThru: string;
    owner: string;
    0: BigNumber;
    1: string;
    2: string;
    3: string;
    4: string;
  }>;

  billboardCount(overrides?: CallOverrides): Promise<BigNumber>;

  "billboardCount()"(overrides?: CallOverrides): Promise<BigNumber>;

  billboards(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    id: BigNumber;
    description: string;
    parcel: string;
    realm: string;
    rate: BigNumber;
    owner: string;
    0: BigNumber;
    1: string;
    2: string;
    3: string;
    4: BigNumber;
    5: string;
  }>;

  "billboards(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    id: BigNumber;
    description: string;
    parcel: string;
    realm: string;
    rate: BigNumber;
    owner: string;
    0: BigNumber;
    1: string;
    2: string;
    3: string;
    4: BigNumber;
    5: string;
  }>;

  createBanner(
    _bannerHash: string,
    _description: string,
    _clickThru: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "createBanner(string,string,string)"(
    _bannerHash: string,
    _description: string,
    _clickThru: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  createBillboard(
    _description: string,
    _parcel: string,
    _realm: string,
    _rate: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "createBillboard(string,string,string,uint256)"(
    _description: string,
    _parcel: string,
    _realm: string,
    _rate: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  createFlight(
    _description: string,
    _bannerId: BigNumberish,
    _billboardId: BigNumberish,
    _rate: BigNumberish,
    _startDate: BigNumberish,
    _endDate: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "createFlight(string,uint256,uint256,uint256,uint256,uint256)"(
    _description: string,
    _bannerId: BigNumberish,
    _billboardId: BigNumberish,
    _rate: BigNumberish,
    _startDate: BigNumberish,
    _endDate: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  flightCount(overrides?: CallOverrides): Promise<BigNumber>;

  "flightCount()"(overrides?: CallOverrides): Promise<BigNumber>;

  flights(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    id: BigNumber;
    description: string;
    bannerId: BigNumber;
    billboardId: BigNumber;
    rate: BigNumber;
    startDate: BigNumber;
    endDate: BigNumber;
    0: BigNumber;
    1: string;
    2: BigNumber;
    3: BigNumber;
    4: BigNumber;
    5: BigNumber;
    6: BigNumber;
  }>;

  "flights(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    id: BigNumber;
    description: string;
    bannerId: BigNumber;
    billboardId: BigNumber;
    rate: BigNumber;
    startDate: BigNumber;
    endDate: BigNumber;
    0: BigNumber;
    1: string;
    2: BigNumber;
    3: BigNumber;
    4: BigNumber;
    5: BigNumber;
    6: BigNumber;
  }>;

  name(overrides?: CallOverrides): Promise<string>;

  "name()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    bannerCount(overrides?: CallOverrides): Promise<BigNumber>;

    "bannerCount()"(overrides?: CallOverrides): Promise<BigNumber>;

    banners(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      id: BigNumber;
      hash: string;
      description: string;
      clickThru: string;
      owner: string;
      0: BigNumber;
      1: string;
      2: string;
      3: string;
      4: string;
    }>;

    "banners(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      id: BigNumber;
      hash: string;
      description: string;
      clickThru: string;
      owner: string;
      0: BigNumber;
      1: string;
      2: string;
      3: string;
      4: string;
    }>;

    billboardCount(overrides?: CallOverrides): Promise<BigNumber>;

    "billboardCount()"(overrides?: CallOverrides): Promise<BigNumber>;

    billboards(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      id: BigNumber;
      description: string;
      parcel: string;
      realm: string;
      rate: BigNumber;
      owner: string;
      0: BigNumber;
      1: string;
      2: string;
      3: string;
      4: BigNumber;
      5: string;
    }>;

    "billboards(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      id: BigNumber;
      description: string;
      parcel: string;
      realm: string;
      rate: BigNumber;
      owner: string;
      0: BigNumber;
      1: string;
      2: string;
      3: string;
      4: BigNumber;
      5: string;
    }>;

    createBanner(
      _bannerHash: string,
      _description: string,
      _clickThru: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "createBanner(string,string,string)"(
      _bannerHash: string,
      _description: string,
      _clickThru: string,
      overrides?: CallOverrides
    ): Promise<void>;

    createBillboard(
      _description: string,
      _parcel: string,
      _realm: string,
      _rate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "createBillboard(string,string,string,uint256)"(
      _description: string,
      _parcel: string,
      _realm: string,
      _rate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    createFlight(
      _description: string,
      _bannerId: BigNumberish,
      _billboardId: BigNumberish,
      _rate: BigNumberish,
      _startDate: BigNumberish,
      _endDate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "createFlight(string,uint256,uint256,uint256,uint256,uint256)"(
      _description: string,
      _bannerId: BigNumberish,
      _billboardId: BigNumberish,
      _rate: BigNumberish,
      _startDate: BigNumberish,
      _endDate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    flightCount(overrides?: CallOverrides): Promise<BigNumber>;

    "flightCount()"(overrides?: CallOverrides): Promise<BigNumber>;

    flights(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      id: BigNumber;
      description: string;
      bannerId: BigNumber;
      billboardId: BigNumber;
      rate: BigNumber;
      startDate: BigNumber;
      endDate: BigNumber;
      0: BigNumber;
      1: string;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
      5: BigNumber;
      6: BigNumber;
    }>;

    "flights(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      id: BigNumber;
      description: string;
      bannerId: BigNumber;
      billboardId: BigNumber;
      rate: BigNumber;
      startDate: BigNumber;
      endDate: BigNumber;
      0: BigNumber;
      1: string;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
      5: BigNumber;
      6: BigNumber;
    }>;

    name(overrides?: CallOverrides): Promise<string>;

    "name()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    BannerCreated(_banner: null): EventFilter;

    BillboardCreated(_billboard: null): EventFilter;

    FlightCreated(_flight: null): EventFilter;
  };

  estimateGas: {
    bannerCount(overrides?: CallOverrides): Promise<BigNumber>;

    "bannerCount()"(overrides?: CallOverrides): Promise<BigNumber>;

    banners(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "banners(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    billboardCount(overrides?: CallOverrides): Promise<BigNumber>;

    "billboardCount()"(overrides?: CallOverrides): Promise<BigNumber>;

    billboards(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "billboards(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createBanner(
      _bannerHash: string,
      _description: string,
      _clickThru: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "createBanner(string,string,string)"(
      _bannerHash: string,
      _description: string,
      _clickThru: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    createBillboard(
      _description: string,
      _parcel: string,
      _realm: string,
      _rate: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "createBillboard(string,string,string,uint256)"(
      _description: string,
      _parcel: string,
      _realm: string,
      _rate: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    createFlight(
      _description: string,
      _bannerId: BigNumberish,
      _billboardId: BigNumberish,
      _rate: BigNumberish,
      _startDate: BigNumberish,
      _endDate: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "createFlight(string,uint256,uint256,uint256,uint256,uint256)"(
      _description: string,
      _bannerId: BigNumberish,
      _billboardId: BigNumberish,
      _rate: BigNumberish,
      _startDate: BigNumberish,
      _endDate: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    flightCount(overrides?: CallOverrides): Promise<BigNumber>;

    "flightCount()"(overrides?: CallOverrides): Promise<BigNumber>;

    flights(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "flights(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    "name()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    bannerCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "bannerCount()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    banners(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "banners(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    billboardCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "billboardCount()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    billboards(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "billboards(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createBanner(
      _bannerHash: string,
      _description: string,
      _clickThru: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "createBanner(string,string,string)"(
      _bannerHash: string,
      _description: string,
      _clickThru: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    createBillboard(
      _description: string,
      _parcel: string,
      _realm: string,
      _rate: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "createBillboard(string,string,string,uint256)"(
      _description: string,
      _parcel: string,
      _realm: string,
      _rate: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    createFlight(
      _description: string,
      _bannerId: BigNumberish,
      _billboardId: BigNumberish,
      _rate: BigNumberish,
      _startDate: BigNumberish,
      _endDate: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "createFlight(string,uint256,uint256,uint256,uint256,uint256)"(
      _description: string,
      _bannerId: BigNumberish,
      _billboardId: BigNumberish,
      _rate: BigNumberish,
      _startDate: BigNumberish,
      _endDate: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    flightCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "flightCount()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    flights(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "flights(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "name()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
